import ImgProfile from '../assets/profile.png';
export const NavbarMenuAdmin = [
    {
      id: 1,
      title: "Usuarios",
      link: "#",
    },
    {
      id: 2,
      title: "Polizas",
      link: "#",
    },
    {
      id: 3,
      title: "Reportes",
      link: "#",
    }
  ];

  export const UsuariosMock = [
    {
      id: 1,
      dni: "12345678",
      nombre: "Carlos",
      apellido: "González",
      correo: "carlos.gonzalez@email.com",
      imageUrl: ImgProfile,
      telefono: "987654321",
      direccion: "Av. Principal 123, Lima",
    },
    {
      id: 2,
      dni: "23456789",
      nombre: "María",
      apellido: "Ramírez",
      correo: "maria.ramirez@email.com",
      imageUrl: ImgProfile,
      telefono: "912345678",
      direccion: "Jr. Los Olivos 456, Cusco",
    },
    {
      id: 3,
      dni: "34567890",
      nombre: "Juan",
      apellido: "Fernández",
      correo: "juan.fernandez@email.com",
      imageUrl: ImgProfile,
      telefono: "965432187",
      direccion: "Calle Las Flores 789, Arequipa",
    },
    {
      id: 4,
      dni: "45678901",
      nombre: "Ana",
      apellido: "López",
      correo: "ana.lopez@email.com",
      imageUrl: ImgProfile,
      telefono: "987341256",
      direccion: "Av. Central 321, Trujillo",
    },
    {
      id: 5,
      dni: "56789012",
      nombre: "Luis",
      apellido: "Torres",
      correo: "luis.torres@email.com",
      imageUrl: ImgProfile,
      telefono: "932187654",
      direccion: "Jr. San Martín 654, Chiclayo",
    },
    {
      id: 6,
      dni: "67890123",
      nombre: "Elena",
      apellido: "Gutiérrez",
      correo: "elena.gutierrez@email.com",
      imageUrl: ImgProfile,
      telefono: "954321876",
      direccion: "Calle Mayor 987, Piura",
    },
    {
      id: 7,
      dni: "78901234",
      nombre: "Miguel",
      apellido: "Castro",
      correo: "miguel.castro@email.com",
      imageUrl: ImgProfile,
      telefono: "987612345",
      direccion: "Av. Perú 456, Tacna",
    },
    {
      id: 8,
      dni: "89012345",
      nombre: "Rosa",
      apellido: "Vega",
      correo: "rosa.vega@email.com",
      imageUrl: ImgProfile,
      telefono: "921234567",
      direccion: "Jr. Amazonas 789, Puno",
    },
    {
      id: 9,
      dni: "90123456",
      nombre: "Pedro",
      apellido: "Mendoza",
      correo: "pedro.mendoza@email.com",
      imageUrl: ImgProfile,
      telefono: "987654321",
      direccion: "Calle Real 654, Ica",
    },
    {
      id: 10,
      dni: "01234567",
      nombre: "Laura",
      apellido: "Salas",
      correo: "laura.salas@email.com",
      imageUrl: ImgProfile,
      telefono: "941256783",
      direccion: "Av. El Sol 321, Ayacucho",
    },
    {
      id: 11,
      dni: "12345679",
      nombre: "Gabriel",
      apellido: "Ortega",
      correo: "gabriel.ortega@email.com",
      imageUrl: ImgProfile,
      telefono: "954789123",
      direccion: "Jr. Libertad 123, Huancayo",
    },
    {
      id: 12,
      dni: "23456780",
      nombre: "Isabel",
      apellido: "Silva",
      correo: "isabel.silva@email.com",
      imageUrl: ImgProfile,
      telefono: "987654123",
      direccion: "Calle Norte 456, Cajamarca",
    },
    {
      id: 13,
      dni: "34567891",
      nombre: "Jorge",
      apellido: "Navarro",
      correo: "jorge.navarro@email.com",
      imageUrl: ImgProfile,
      telefono: "932165478",
      direccion: "Av. Los Andes 789, Moquegua",
    },
    {
      id: 14,
      dni: "45678912",
      nombre: "Sofía",
      apellido: "Flores",
      correo: "sofia.flores@email.com",
      imageUrl: ImgProfile,
      telefono: "921876543",
      direccion: "Jr. Bolívar 654, Tumbes",
    },
    {
      id: 15,
      dni: "56789023",
      nombre: "Raúl",
      apellido: "Suárez",
      correo: "raul.suarez@email.com",
      imageUrl: ImgProfile,
      telefono: "987654213",
      direccion: "Calle Miraflores 321, Madre de Dios",
    },
    {
      id: 16,
      dni: "67890134",
      nombre: "Lucía",
      apellido: "Campos",
      correo: "lucia.campos@email.com",
      imageUrl: ImgProfile,
      telefono: "932178654",
      direccion: "Av. Central 456, Junín",
    },
    {
      id: 17,
      dni: "78901245",
      nombre: "Diego",
      apellido: "Vásquez",
      correo: "diego.vasquez@email.com",
      imageUrl: ImgProfile,
      telefono: "954321789",
      direccion: "Jr. San José 789, Ucayali",
    },
    {
      id: 18,
      dni: "89012356",
      nombre: "Patricia",
      apellido: "Pérez",
      correo: "patricia.perez@email.com",
      imageUrl: ImgProfile,
      telefono: "987612534",
      direccion: "Calle Las Palmeras 654, Loreto",
    },
    {
      id: 19,
      dni: "90123467",
      nombre: "Andrés",
      apellido: "Morales",
      correo: "andres.morales@email.com",
      imageUrl: ImgProfile,
      telefono: "921356478",
      direccion: "Av. Grau 321, Apurímac",
    },
    {
      id: 20,
      dni: "01234578",
      nombre: "Carmen",
      apellido: "Cruz",
      correo: "carmen.cruz@email.com",
      imageUrl: ImgProfile,
      telefono: "932478123",
      direccion: "Jr. Victoria 456, Pasco",
    },
  ];
  
  